# Generated by Django 5.2.4 on 2025-07-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=200)),
                ('year_released', models.DateField()),
                ('genre', models.CharField(max_length=30)),
                ('thumbnail', models.ImageField(upload_to='cinema/thumbnails', verbose_name='Movie Poster')),
            ],
        ),
    ]
