# Generated by Django 5.2.4 on 2025-07-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
