# Generated by Django 5.2.4 on 2025-07-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_cinema_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cinema',
            new_name='Movie',
        ),
    ]
