# Generated by Django 5.2.4 on 2025-08-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_user_session_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='audience_number',
            field=models.IntegerField(default=1),
        ),
    ]
