# Generated by Django 5.2.4 on 2025-08-12 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0011_movie_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='company',
        ),
    ]
