# Generated by Django 5.2.4 on 2025-08-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0012_remove_movie_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='company',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
